// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANI5jAHqXtnQGtVot6mypSJA9aTgGehM0',
    appId: '1:641231087477:android:f936db83d86f47a628153c',
    messagingSenderId: '641231087477',
    projectId: 'project-absensi-wkn',
    storageBucket: 'project-absensi-wkn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5T3nMGZe63eM9130lm1zuJMAQ6Xsg5MY',
    appId: '1:641231087477:ios:7163df14eea2927028153c',
    messagingSenderId: '641231087477',
    projectId: 'project-absensi-wkn',
    storageBucket: 'project-absensi-wkn.firebasestorage.app',
    iosBundleId: 'com.example.flutterMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWa7wjIBkUPqPaTyuMhQFJ9l8T-k8IVMU',
    appId: '1:641231087477:web:76fae7e7fe7c52ea28153c',
    messagingSenderId: '641231087477',
    projectId: 'project-absensi-wkn',
    authDomain: 'project-absensi-wkn.firebaseapp.com',
    storageBucket: 'project-absensi-wkn.firebasestorage.app',
    measurementId: 'G-G3PV99BZT3',
  );
}
